### ISSUE TITLE
[LOGIC] - BST REMOVE NODE

### ISSUE THREAD

**Issue by vikkastiwari** [shree1999/Data-Structures-and-Algorithms#16]
#### In the below code snippet from BST under the `deleteNode` function. The logic is quite unclear for me like how it is working for the below case.
```
            Root
           /    \
     child1   child2
     /   \      
 Null   leaf1
```
#### Code Snippet
```
else if (temp->left == NULL || temp->right == NULL)
                {
                    cout << "We are deleting parent node which have one child" << endl;
                    if (temp->left != NULL)
                    {
                        parent->left = temp->left;
                    }
                    else
                    {
                        parent->right = temp->right;
                    }
                    free(temp);
                    return;
                }
```
### If you can put light on it then it would be a great help :)

**Comment by shree1999** [comment]
@vikkastiwari I hope my explanation reaches your expectation
So, According to your question we have to delete the node marked as `Child1`. 

So after iterating we find that `temp` pointer is pointing to the `child1` and the `parent` pointer is pointing to the `root` node. hope you understand how...

Now, according to your tree structure, `temp->left` is null so this means left side of  `child1` is null or empty so if I could make the `parent` node point to the left side of `child1` then we can bypass the `child1` hence removing it from the tree

hence we have `parent->left = temp->left` saying that parent left side  will be now null and hence making `child1` unreachable.

and to free the memory we use free(temp);

Hope, this helps
