### ISSUE TITLE
Delete Function [BST]

### ISSUE THREAD

**Issue by vikkastiwari** [shree1999/Data-Structures-and-Algorithms#18]
```
cout << "Deleting Node which has two children" << endl;
// in this case we need to find the pre-order successor.
Node *t = temp->right;
if (t->left == NULL && t->right == NULL)
{
    temp->data = t->data;
    temp->right = NULL;
    free(t);
    return;
}
else if (t->left == NULL && t->right != NULL)
{
    temp->data = t->data;
    temp->right = t->right;
    free(t);
    return;
}
while (t->left != NULL)
{
    parent = t;
    t = t->left;
}
temp->data = t->data;
parent->left = NULL;
free(t);
return;
```
In the above code snippet of the Delete function from BST.  Please mention cases that we are handling.

**Comment by shree1999** [comment]
Can you please elaborate?

**Comment by vikkastiwari** [comment]
Like we are handling some cases in that block where we have to delete a node that has two child nodes?
Can you please mention how we are managing different cases in if-else like what is the approach ...

**Comment by shree1999** [comment]
Hi @vikkastiwari  Sorry for the late response I will do my best to explain it 
The first line `t = temp-> right` already gives us idea that whatever number we choose to replace temp with will be greater then temp. where `temp` is the node we want to delete/remove.

Note **t** is the same variable used in the first line of the code segment

Also, we don't care about left children of **temp** afterall we have to preserve rules of BST 😉

Now, 
in the first case we have something like this
```
temp
 /    \
x      t
      /  \
   null null
```
hence we have, 
 **t** is the `right child node` of temp and **t** doesn't have any children so we take the data of **t** and replace with data of **temp** and remove **t**. 

In the second case **t** has only child node at the right and it can be of any number something like this
```
temp
 /   \
x      t
         \
           a
             \
               blah blah
```
so now in the above we are replacing **temp** data with **t** data and linking `temp of right to t of right`. that is **temp** right is pointing to **a**. and then free **t**

In the last condition that is the `while loop` we have, 
```
temp
 /   \
x      t
      /   \
    b      a
   /         \
 c             blah blah
```
that is there is some children nodes on the left of **t** so then we traverse till the last left child in this case **c** and the swap the data of **c** and  **temp** and deleting **c** in this way we are still preserving the rules of**BST**.

Hope this helps and sorry for rate reply **busy with office work** 👀

**Comment by vikkastiwari** [comment]
Thanks for taking out time and for this simple explanation.
I was having my exams last week that's why I lost track...
